pub trait Logger {
    fn log(mut self)
}

pub struct Console {}
impl Logger for Console {
    fn log(mut self) {}
}

pub struct Storage {
    value: u64,
}

pub fn log_once()
  uses (mut logger: Logger)
{
    logger.log()
}

pub fn mint(_ amount: u64)
  uses (mut st: Storage)
{
    st.value += amount
}

pub fn do_both()
  uses (mut Storage, mut Logger)
{
    mint(1)
    log_once()
}

pub fn provide_both() {
    let mut st = Storage { value: 0 }
    with (st, Console {}) {
        do_both()
    }
}
