struct Foo {}

fn copy_ok(x: u256) {
    let mut y = x
    let _z = x
    y += 1
}

fn explicit_mut_handle_bad(mut x: own u256) {
    let mut h: mut u256 = mut x
    h = 1
}

fn inferred_mut_handle_bad(mut x: own u256) {
    let mut h = mut x
    h = 1
}

fn noncopy_view_origin_bad(x: Foo) {
    let mut y = x
}

fn nested_pattern_bad(mut x: own u256) {
    let (mut h, _): (mut u256, u256) = (mut x, 1)
    h = 1
}
