/// ### Calculation helper functions
pub mod calculations {
  /// A function that returns `3`
  pub fn return_three() -> u32 {
    3
  }

  /// ## A function that returns 4
  pub fn return_four() {
    4
  }

  /// which one is it?
  pub mod ambiguous {

  }
  /// is it this one?
  pub fn ambiguous() {}
}

pub enum Color {
  Red,
  Green,
  Blue
}

pub fn is_red(c: Color) -> bool {
  match c {
    Color::Red => true
    Color::Green => false
    Color::Blue => false
  }
}
